### ISSUE TITLE
How start with this template?

### ISSUE THREAD

**Issue by estvmachine** [number-4/web-app#3]
Hi, i download this skeleton. But what i need to do now?

I think this was a more complete esqueleton?

**Comment by clthck** [comment]
Hi @estvmachine this app skeleton is based on CakePHP 3. Please refer to [CakePHP Cookbook](http://book.cakephp.org/3.0/en/quickstart.html) to get started with the app.

**Comment by estvmachine** [comment]
The question is more for the screen in the READme, i think this include scss or css and demo.

**Comment by clthck** [comment]
I'm sorry but this repo is no longer maintained. I'm closing all the issues. Thanks for your interest.
